SYSTEM_UTILS=(
  htop
  btop
  lazygit
  stow
  ripgrep
  fzf
)

DEV_TOOLS=(
  vim
  yazi
  bat
  zsh
  oh-my-posh
  neovim
  tmux
  git
  docker
)

DEV_TOOLS_CASKS=(
  ghostty
  visual-studio-code
)

BROWSERS=(
  firefox
  google-chrome
)

MEDIA=(
  vlc
  spotify
)

FONTS=(
  font-jetbrains-mono-nerd-font
)

MAC_ONLY_CASKS=(
  rectangle
  flux-app
  oversight
)
